version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    command: sleep infinity
    environment:
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ..:/src
